# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b3b5a6ac7ddcb95bdd1f1105b483f3bebd519257b02949e51b2272d2eddd331837c67d952d17d7c3d64fff8ba642616907e9ce8c68dfddd1224d3ffed092dfcd

test:
  secret_key_base: 7662c295a7e3350e3cdd17a46e3af48dc3a5571ec1fc14caeeaa8ec55e478c197755714fc14cf5433b270a26f2fdcfe88af8ff54f5d0cd95a9c333dab0a1afed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
